version: '3'
services:
  nginx:
    image: nginx:1.17.2
    ports:
      - 80:80
    volumes:
      - ./../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php-fpm

  php-fpm:
    build: php-fpm
    volumes:
      - ./../:/var/www